version: '3'

services:
  backend:
    build: ./backend
    working_dir: /var/www
    command: ./entrypoint.sh
    ports:
      - "11111:11111"
    volumes:
      - ./backend:/var/www

  frontend:
    image: node:12
    working_dir: /src/frontend
    command: ./entrypoint.sh
    ports:
      - "11112:11112"
    volumes:
      - ./frontend:/src/frontend
